import type { AttackScenario } from '../types';

export const ATTACK_SCENARIOS: AttackScenario[] = [
  {
    id: 'log4shell',
    name: 'Log4Shell (CVE-2021-44228)',
    type: 'RCE via Logging Library',
    cve: 'CVE-2021-44228',
    description: 'Critical RCE vulnerability in Apache Log4j2 affecting millions of Java applications worldwide.',
    year: 2021,
    severity: 'critical',
    entryPoint: 'log4j-core',
    propagationPath: ['log4j-core', 'app-server', 'auth-service', 'database', 'secrets-vault'],
    color: '#ef4444',
    initialNodes: [
      { id: 'log4j-core', label: 'log4j-core', type: 'library', version: '2.14.1', vendor: 'Apache', x: 400, y: 200, status: 'vulnerable', riskLevel: 'critical', cve: 'CVE-2021-44228', description: 'Apache Log4j2 logging library with JNDI injection vulnerability' },
      { id: 'app-server', label: 'App Server', type: 'service', version: '11.0.2', x: 600, y: 150, status: 'safe', riskLevel: 'high', description: 'Main application server' },
      { id: 'auth-service', label: 'Auth Service', type: 'service', version: '3.1.0', x: 700, y: 300, status: 'safe', riskLevel: 'medium', description: 'OAuth2 authentication service' },
      { id: 'database', label: 'PostgreSQL DB', type: 'database', version: '14.2', x: 550, y: 380, status: 'safe', riskLevel: 'high', description: 'Primary database cluster' },
      { id: 'secrets-vault', label: 'Secrets Vault', type: 'service', version: '1.9.4', x: 300, y: 350, status: 'safe', riskLevel: 'critical', description: 'HashiCorp Vault for secret management' },
      { id: 'cdn', label: 'CDN / WAF', type: 'service', version: '2.0', x: 200, y: 150, status: 'safe', riskLevel: 'low', description: 'CloudFront CDN with WAF rules' },
      { id: 'ci-pipeline', label: 'CI Pipeline', type: 'ci', version: 'Jenkins 2.375', x: 150, y: 280, status: 'safe', riskLevel: 'medium', description: 'Jenkins build pipeline' },
      { id: 'npm-registry', label: 'NPM Registry', type: 'registry', version: 'internal', x: 350, y: 80, status: 'safe', riskLevel: 'medium', description: 'Internal package registry' },
      { id: 'api-gateway', label: 'API Gateway', type: 'api', version: '3.4.1', x: 500, y: 50, status: 'safe', riskLevel: 'medium', description: 'Kong API gateway' },
    ],
    initialEdges: [
      { id: 'e1', source: 'api-gateway', target: 'app-server', type: 'data' },
      { id: 'e2', source: 'app-server', target: 'log4j-core', type: 'dependency' },
      { id: 'e3', source: 'app-server', target: 'auth-service', type: 'auth' },
      { id: 'e4', source: 'app-server', target: 'database', type: 'data' },
      { id: 'e5', source: 'auth-service', target: 'secrets-vault', type: 'auth' },
      { id: 'e6', source: 'cdn', target: 'api-gateway', type: 'data' },
      { id: 'e7', source: 'ci-pipeline', target: 'npm-registry', type: 'build' },
      { id: 'e8', source: 'npm-registry', target: 'app-server', type: 'build' },
      { id: 'e9', source: 'database', target: 'secrets-vault', type: 'data' },
    ],
  },
  {
    id: 'solarwinds',
    name: 'SolarWinds SUNBURST',
    type: 'Build Pipeline Backdoor',
    cve: 'CVE-2020-10148',
    description: 'Nation-state attackers injected malicious code into SolarWinds Orion software build process, affecting 18,000+ organizations.',
    year: 2020,
    severity: 'critical',
    entryPoint: 'build-server',
    propagationPath: ['build-server', 'orion-platform', 'azure-ad', 'email-server', 'firewall-config'],
    color: '#f97316',
    initialNodes: [
      { id: 'build-server', label: 'Build Server', type: 'build', version: 'MSBuild 16', vendor: 'SolarWinds', x: 300, y: 150, status: 'vulnerable', riskLevel: 'critical', cve: 'CVE-2020-10148', description: 'Compromised build server injecting SUNBURST backdoor' },
      { id: 'orion-platform', label: 'Orion Platform', type: 'service', version: '2020.2.1', x: 500, y: 150, status: 'safe', riskLevel: 'critical', description: 'SolarWinds IT monitoring platform' },
      { id: 'azure-ad', label: 'Azure AD', type: 'api', version: 'cloud', x: 650, y: 100, status: 'safe', riskLevel: 'high', description: 'Azure Active Directory' },
      { id: 'email-server', label: 'Exchange Server', type: 'service', version: '2016 CU19', x: 650, y: 250, status: 'safe', riskLevel: 'high', description: 'Microsoft Exchange email server' },
      { id: 'firewall-config', label: 'Firewall Rules', type: 'service', version: 'Cisco ASA', x: 450, y: 300, status: 'safe', riskLevel: 'critical', description: 'Network perimeter firewall' },
      { id: 'source-control', label: 'Source Control', type: 'ci', version: 'Git/SVN', x: 150, y: 150, status: 'safe', riskLevel: 'medium', description: 'Version control system' },
      { id: 'code-signing', label: 'Code Signing', type: 'ci', version: 'PKI', x: 150, y: 300, status: 'safe', riskLevel: 'high', description: 'Certificate signing authority' },
      { id: 'update-server', label: 'Update Server', type: 'registry', version: 'internal', x: 350, y: 350, status: 'safe', riskLevel: 'high', description: 'Software distribution server' },
    ],
    initialEdges: [
      { id: 'e1', source: 'source-control', target: 'build-server', type: 'build' },
      { id: 'e2', source: 'build-server', target: 'code-signing', type: 'build' },
      { id: 'e3', source: 'build-server', target: 'orion-platform', type: 'build' },
      { id: 'e4', source: 'code-signing', target: 'update-server', type: 'build' },
      { id: 'e5', source: 'orion-platform', target: 'azure-ad', type: 'auth' },
      { id: 'e6', source: 'orion-platform', target: 'email-server', type: 'data' },
      { id: 'e7', source: 'orion-platform', target: 'firewall-config', type: 'data' },
      { id: 'e8', source: 'update-server', target: 'orion-platform', type: 'dependency' },
    ],
  },
  {
    id: 'xz-utils',
    name: 'XZ Utils Backdoor',
    type: 'Open Source Trojan',
    cve: 'CVE-2024-3094',
    description: 'Two-year social engineering campaign culminating in a backdoor in XZ Utils compression library, nearly compromising SSH on Linux systems.',
    year: 2024,
    severity: 'critical',
    entryPoint: 'xz-utils',
    propagationPath: ['xz-utils', 'openssh', 'systemd', 'linux-distro', 'cloud-infra'],
    color: '#8b5cf6',
    initialNodes: [
      { id: 'xz-utils', label: 'xz-utils', type: 'library', version: '5.6.1', vendor: 'OSS', x: 350, y: 200, status: 'vulnerable', riskLevel: 'critical', cve: 'CVE-2024-3094', description: 'Compromised XZ compression library with SSH backdoor' },
      { id: 'openssh', label: 'OpenSSH', type: 'service', version: '9.6p1', x: 550, y: 150, status: 'safe', riskLevel: 'critical', description: 'SSH server daemon linked with liblzma' },
      { id: 'systemd', label: 'systemd', type: 'service', version: '255', x: 550, y: 300, status: 'safe', riskLevel: 'high', description: 'Linux init system and service manager' },
      { id: 'linux-distro', label: 'Debian/Ubuntu', type: 'registry', version: 'testing', x: 700, y: 200, status: 'safe', riskLevel: 'high', description: 'Linux distribution package manager' },
      { id: 'cloud-infra', label: 'Cloud Infra', type: 'service', version: 'AWS EC2', x: 700, y: 350, status: 'safe', riskLevel: 'critical', description: 'Cloud infrastructure running affected OS' },
      { id: 'github-repo', label: 'GitHub Repo', type: 'ci', version: 'main', x: 150, y: 200, status: 'safe', riskLevel: 'medium', description: 'xz-utils GitHub repository' },
      { id: 'upstream-mirror', label: 'Upstream Mirror', type: 'registry', version: 'cdn', x: 200, y: 350, status: 'safe', riskLevel: 'medium', description: 'Package distribution mirrors' },
    ],
    initialEdges: [
      { id: 'e1', source: 'github-repo', target: 'xz-utils', type: 'build' },
      { id: 'e2', source: 'xz-utils', target: 'openssh', type: 'dependency' },
      { id: 'e3', source: 'xz-utils', target: 'systemd', type: 'dependency' },
      { id: 'e4', source: 'upstream-mirror', target: 'linux-distro', type: 'build' },
      { id: 'e5', source: 'linux-distro', target: 'xz-utils', type: 'dependency' },
      { id: 'e6', source: 'openssh', target: 'cloud-infra', type: 'auth' },
      { id: 'e7', source: 'systemd', target: 'cloud-infra', type: 'data' },
    ],
  },
  {
    id: 'codecov',
    name: 'Codecov Bash Uploader',
    type: 'CI/CD Compromise',
    description: 'Attacker modified Codecov\'s Bash Uploader script to exfiltrate environment variables and tokens from CI pipelines.',
    year: 2021,
    severity: 'high',
    entryPoint: 'codecov-script',
    propagationPath: ['codecov-script', 'github-actions', 'aws-credentials', 'prod-database'],
    color: '#06b6d4',
    initialNodes: [
      { id: 'codecov-script', label: 'Codecov Uploader', type: 'ci', version: 'bash-1.0.3', vendor: 'Codecov', x: 300, y: 200, status: 'vulnerable', riskLevel: 'high', description: 'Tampered Bash uploader script' },
      { id: 'github-actions', label: 'GitHub Actions', type: 'ci', version: 'cloud', x: 500, y: 120, status: 'safe', riskLevel: 'high', description: 'CI/CD pipeline with secrets' },
      { id: 'aws-credentials', label: 'AWS Keys', type: 'service', version: 'IAM', x: 650, y: 200, status: 'safe', riskLevel: 'critical', description: 'AWS IAM credentials in CI env' },
      { id: 'prod-database', label: 'Prod Database', type: 'database', version: 'RDS PostgreSQL', x: 600, y: 350, status: 'safe', riskLevel: 'critical', description: 'Production database instance' },
      { id: 'docker-registry', label: 'Docker Registry', type: 'registry', version: 'ECR', x: 400, y: 350, status: 'safe', riskLevel: 'medium', description: 'Container image registry' },
      { id: 'attacker-server', label: 'Attacker C2', type: 'api', version: 'external', x: 150, y: 200, status: 'vulnerable', riskLevel: 'critical', description: 'Attacker command & control server' },
    ],
    initialEdges: [
      { id: 'e1', source: 'github-actions', target: 'codecov-script', type: 'build' },
      { id: 'e2', source: 'codecov-script', target: 'attacker-server', type: 'data' },
      { id: 'e3', source: 'github-actions', target: 'aws-credentials', type: 'auth' },
      { id: 'e4', source: 'aws-credentials', target: 'prod-database', type: 'data' },
      { id: 'e5', source: 'aws-credentials', target: 'docker-registry', type: 'auth' },
      { id: 'e6', source: 'attacker-server', target: 'aws-credentials', type: 'data' },
    ],
  },
];

export const NODE_COLORS = {
  safe: { fill: '#1e293b', stroke: '#334155', text: '#94a3b8' },
  vulnerable: { fill: '#431407', stroke: '#f97316', text: '#fb923c' },
  compromised: { fill: '#450a0a', stroke: '#ef4444', text: '#f87171' },
  patched: { fill: '#052e16', stroke: '#22c55e', text: '#4ade80' },
};

export const NODE_TYPE_ICONS: Record<string, string> = {
  service: '⚙️',
  library: '📦',
  ci: '🔧',
  registry: '🗄️',
  database: '🗃️',
  api: '🔌',
  build: '🏗️',
};
